services:
  - type: web
    name: devops-api-prd
    runtime: image
    plan: free
    region: ohio

    image:
      url: docker.io/itzvictorxd/devops-api:latest

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: PORT
        value: 10000
