name: Compilacion DevOps

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4

      - name: Compilacion Docker
        shell: powershell
        run: |
          docker build --target publish-artifacts --output type=local,dest=.\publish .

      - name: Compresion de Publicacion
        run: Compress-Archive -Path ./publish/* -DestinationPath ./artefacto.zip

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ./artifact/artefacto.zip
