name: Compilacion DevOps - Hosted

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'DevOps/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'DevOps/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compilacion Docker
        shell: powershell
        run: |
          docker build --target publish-artifacts --output type=local,dest=.\publish .

      - name: Compresion de Publicacion
        shell: powershell
        run: |
          # tu script actual aquí

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ./artefacto.zip
