name: Compilacion DevOps - Hosted

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'DevOps/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'DevOps/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compilacion Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          target: publish-artifacts
          outputs: type=local,dest=./publish

      - name: Copiar archivo extra
        run: |
          cp Dockerfile ./publish/

      - name: Comprimir Publicacion
        run: |
          cd publish
          zip -r ../artefacto.zip .

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ./artefacto.zip
