name: Publicacion Imagen

on:
  workflow_run:
    workflows: [Compilacion DevOps]
    types: [completed]
    branches: [main, dev]

  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  Publicacion:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    runs-on: self-hosted

    steps:
      - name: Limpiar Workspace
        run: |
          Remove-Item "$env:GITHUB_WORKSPACE\*" -Recurse -Force -ErrorAction SilentlyContinue
          
      - name: Descargar Artefacto
        uses: actions/download-artifact@v4
        with:
          name: app-package
          path: descarga
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraer artefactos
        run: |
          mkdir -p extraido
          Expand-Archive -Path ".\descarga\artefacto.zip" -DestinationPath ".\extraido" -Force

      - name: Crear Imagen
        shell: powershell
        run: |
          docker build -f ./DevOps/DevOps/extraido/Dockerfile -t itzvictorxd/devops-api:1.0 .

      - name: Publicar Imagen
        shell: powershell
        run: |
          docker push itzvictorxd/devops-api:1.0
